export enum StatusProcesso {
  RASCUNHO = 'RASCUNHO',
  EM_ANDAMENTO = 'EM_ANDAMENTO',
  AGUARDANDO_DOCUMENTOS = 'AGUARDANDO_DOCUMENTOS',
  EM_JULGAMENTO = 'EM_JULGAMENTO',
  CONCLUIDO = 'CONCLUIDO',
  ARQUIVADO = 'ARQUIVADO'
}

export enum TipoProcesso {
  CIVIL = 'CIVIL',
  PENAL = 'PENAL',
  TRABALHISTA = 'TRABALHISTA',
  ADMINISTRATIVO = 'ADMINISTRATIVO',
  CONSUMIDOR = 'CONSUMIDOR',
  FAMILIAR = 'FAMILIAR',
  PREVIDENCIARIO = 'PREVIDENCIARIO',
  OUTROS = 'OUTROS'
}