export enum StatusProcesso {
  RASCUNHO = 'RASCUNHO',
  PENDENTE = 'PENDENTE',
  EM_ANALISE = 'EM_ANALISE',
  ACEITO = 'ACEITO',
  REJEITADO = 'REJEITADO',
  AGUARDANDO_DADOS = 'AGUARDANDO_DADOS',
  DADOS_ENVIADOS = 'DADOS_ENVIADOS',
  AGUARDANDO_ANALISE_DADOS = 'AGUARDANDO_ANALISE_DADOS',
  EM_ANDAMENTO = 'EM_ANDAMENTO',
  PROTOCOLADO = 'PROTOCOLADO',
  EM_JULGAMENTO = 'EM_JULGAMENTO',
  CONCLUIDO = 'CONCLUIDO',
  ARQUIVADO = 'ARQUIVADO'
}

export enum TipoProcesso {
  CIVIL = 'CIVIL',
  PENAL = 'PENAL',
  TRABALHISTA = 'TRABALHISTA',
  ADMINISTRATIVO = 'ADMINISTRATIVO',
  CONSUMIDOR = 'CONSUMIDOR',
  FAMILIAR = 'FAMILIAR',
  PREVIDENCIARIO = 'PREVIDENCIARIO',
  OUTROS = 'OUTROS'
}